### PR TITLE
Feature : Show and hide columns in tables

### PR DESCRIPTION
**Pull request by PhRX**
When there are too many columns, the table views get too cluttered. A menu was added allowing to show and hide specific columns or groups of columns.

Replaces deleted PR #197 .

### CODE REVIEW

**Comment by PhRX** [comment]
Commit 58dd0f5 reverts all previous commits from 13de748 up to and including 1e1e31e, so please ignore those commits in the PR commit list.

**Comment by RichardWarburton** [comment]
Thanks for the PR, Just one question - what is the license and source for the images that you've included?

**Comment by PhRX** [comment]
I've only added icons from the "Fugue" icon set (see http://p.yusukekamiyamane.com/), under the Creative Commons Attribution 3.0 License.

I've been meaning to put the attribution in a text file in the root dir, but I'm unsure what the name of such a file should be. Would that be "NOTICE" ?

I'll also put it in an "About" dialog if/when I get round to doing that.

**Comment by RichardWarburton** [comment]
Thanks for the PR.

**Pull request merged**
