### PR TITLE
Fix #188 : Flame Graphs

### LINKED ISSUE #188: FlameGraph Issues in FX UI ?
I just read @nitsanw 's great [blog post about Flamegraphs](https://psy-lob-saw.blogspot.ie/2017/02/flamegraphs-intro-fire-for-everyone.html), and after having another look at the flamegraph rendering in the honest profiler JavaFX front-end, it seems to me that there's an issue : the stacks do not seem to be aggregated together properly.

Fundamentally, if I understand it correctly, a flamegraph is "just" a graphic rendition of  the tree view (aggregated by method id), with the roots at the bottom, and rectangles for frames, the width being in proportion to the sample count % in their parent.

If I read the code correctly though, the flame graph collector starts a new FlameTrace whenever the next received stack isn't identical to the previous one. This is then rendered as such without further aggregation.

As a consequence, if only 2 stacks appear in the sample, but they alternate, the result will be highly fragmented.

To put it more explicitly, say that we see : a.b.c() (stack 1) and d.e.f() being called alternatingly 3 times :

- Log events (simplified) :
---   Trace Start
---   Frames for a.b.c
---   Trace Start
---   Frames for d.e.f
---   (repeat the above two more times)

My understanding is that this should be rendered as 2 vertical columns, each with 3 layers, and every block has a sample count of 3.

However, from the code, it seems that this will be rendered as 6 columns, with every block having a sample count of 1.

I'm about to try and "fix" this, but before checking anything in I'd like to get some confirmation that this is indeed an issue, and not based on my misunderstanding the principles.

### PR DESCRIPTION
**Pull request by PhRX**
- Fixed the incorrect aggregation underlying the flamegraph rendering
- Implemented different color scheme for flamegraphs, with an eye on making it configurable from the UI in the future
- Added Flame Diff View comparing flamegraphs, (red/green indicating regression/improvement)
- Allow Flame Graph filtering
- Enable various aggregations (method name, method name + line nr etc.)

- Fixed one non-flamegraph-related regression : in diff view column headers the profile numbers went missing

### CODE REVIEW

**Comment by RichardWarburton** [comment]
Hi @PhRX,

Thanks for the PR. It looks like generally useful stuff, but I've got a few concerns that I've commented on inline in the codebase. I also have a bigger concern - which is that there is no automated tests to demonstrate that these features work. This means that if the code got refactored at a later date then we wouldn't know if it continued to work. Again, thanks for the fix, but I really want to make sure that we're not only adding features but also not just adding technical debt.

  Richard

**Comment by PhRX** [comment]
Hi @RichardWarburton,

I'm not sure which comments in the codebase you're referring to - I'll address them as soon as I know where to find them :)

I'm aware of the lack of tests. It's a byproduct of moving forward fast. I'd be interested in getting pointers to a good JavaFX test framework, I don't know any yet. For now, I can still manually test everything in a couple of minutes, and given that I have a vested interest in having the profiler run correctly, I'll keep doing that until I find the time to automate testing.

Xeers
Philip

**Comment by RichardWarburton** [comment]
Hi @PhRX,

I understand what you mean about moving fast, but I don't think its possible to move forward fast in a sustainable way without having some automated tests. I'm sure you're manually testing things, and that's most appreciated but I think its important to try and keep tests for key functionality automated. https://github.com/TestFX/TestFX looks like it would fit the bill for being able to test Javafx code, how do you feel about it?

**Comment by PhRX** [comment]
Hi @RichardWarburton,

Economically, it made more sense to code first in this case. Adding UI tests would up to now only have generated an extra maintenance load (given that I didn't have an up-front design of the projected end state) with not much benefit in return. Also, my bandwidth is limited. Now that things are that much closer to being stable, it makes more sense to start a test effort.

I'll have a look at TestFX. I'm OK with any framework, as long as it's something which will still be well-maintained in the future. The more it is accepted as "industry standard" the better.
The first tests though will be core tests - the fundaments are the most important thing if the house needs to stay up.

**Comment by PhRX** [comment]
Superseded by upcoming, cleaner PR.

**Pull request closed without merging**
